### ISSUE TITLE
Ein-Teilchen System?

### ISSUE THREAD

**Issue by fefr3d** [tonimueller/LectureWKMBPNumerics_2021#1]
In [AdsorbtionofMonomers](https://github.com/tonimueller/LectureWKMBPNumerics_2021/blob/7677538d040757f27d4c30c266914f562398a032/uebung4/AdsorptionofMonomers.ipynb) Zelle 3:
`# setup system`
`for n in range(numMonos):`
    `gasSimulator = laga.LatticeGasSimulator(box, periodic, 0.0)`
    `newPos = np.random.randint(box[0]-1,size=(3))`
    `gasSimulator.addMonomer(newPos, {})`

Instance wird jedes Mal neu erzeugt, also nur ein Teilchen im System, was benutzt wird, oder übersehe ich etwas?
Scheint ja trotzdem zu klappen, aber dann kann die angegebene Schleife weg?
Hab mit 256 Teilchen probiert und da dauert es dann wesentlich länger...

**Comment by tonimueller** [comment]
Hmm, das stimmt es muss heissen: 
``` python 
# setup system
gasSimulator = laga.LatticeGasSimulator(box, periodic, 0.0)
for n in range(numMonos):  
    newPos = np.random.randint(box[0]-1,size=(3))
    gasSimulator.addMonomer(newPos, {})
```
